"""initial schema

Revision ID: 2412e25c519e
Revises: 
Create Date: 2026-03-04 19:09:53.654605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2412e25c519e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('expense', 'income', 'transfer', name='categorykind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('bank_account', 'credit_card', name='instrumenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('santander_br', 'xp_br', 'bbva_uy', name='instrumentsource'), nullable=False),
    sa.Column('source_instrument_id', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'UYU', name='currency'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_instrument_id')
    )
    op.create_table('categorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('bank_transaction', 'card_transaction', name='targettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id')
    )
    op.create_table('credit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('statement_currency', sa.Enum('BRL', 'USD', 'UYU', name='currency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('created', 'processed', 'failed', name='importstatus'), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_norm', sa.Text(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'UYU', name='currency'), nullable=False),
    sa.Column('source_tx_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_hash')
    )
    op.create_table('credit_card_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('statement_start', sa.Date(), nullable=False),
    sa.Column('statement_end', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'UYU', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'paid', 'partial', name='statementstatus'), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_id', 'statement_start', 'statement_end')
    )
    op.create_table('credit_card_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_card_id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_norm', sa.Text(), nullable=False),
    sa.Column('merchant_raw', sa.Text(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Enum('BRL', 'USD', 'UYU', name='currency'), nullable=False),
    sa.Column('installments_total', sa.Integer(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('source_tx_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['credit_card_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_hash')
    )
    op.create_table('statement_payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('card_statement_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['card_statement_id'], ['credit_card_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement_payment_links')
    op.drop_table('credit_card_transactions')
    op.drop_table('credit_card_statements')
    op.drop_table('bank_transactions')
    op.drop_table('import_batches')
    op.drop_table('credit_cards')
    op.drop_table('categorizations')
    op.drop_table('instruments')
    op.drop_table('categories')
    # ### end Alembic commands ###
