/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_instruments_get"];
        put?: never;
        /** Create Instrument */
        post: operations["create_instrument_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument */
        get: operations["get_instrument_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Instrument */
        patch: operations["update_instrument_instruments__instrument_id__patch"];
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Import Batches */
        get: operations["list_import_batches_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Batch */
        get: operations["get_import_batch_imports__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_imports_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bank-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bank Transactions */
        get: operations["list_bank_transactions_bank_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Card Transactions */
        get: operations["list_card_transactions_card_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Statements */
        get: operations["list_statements_card_statements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_categories__category_id__patch"];
        trace?: never;
    };
    "/categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Categorize */
        post: operations["categorize_categorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorize/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Categorize Bulk */
        post: operations["categorize_bulk_categorize_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorizations/{categorization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Categorization */
        delete: operations["delete_categorization_categorizations__categorization_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spending-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending Summary */
        get: operations["spending_summary_spending_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BankTransactionOut */
        BankTransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Description Raw */
            description_raw: string;
            /** Description Norm */
            description_norm: string;
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            /** Fingerprint Hash */
            fingerprint_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Category Id */
            category_id?: string | null;
            /** Category Name */
            category_name?: string | null;
        };
        /** Body_upload_file_imports_upload_post */
        Body_upload_file_imports_upload_post: {
            /** File */
            file: string;
        };
        /** BulkCategorizeRequest */
        BulkCategorizeRequest: {
            /** Items */
            items: components["schemas"]["CategorizeRequest"][];
        };
        /** BulkCategorizeResult */
        BulkCategorizeResult: {
            /** Updated */
            updated: number;
            /** Created */
            created: number;
        };
        /** CardStatementOut */
        CardStatementOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Credit Card Id
             * Format: uuid
             */
            credit_card_id: string;
            /**
             * Statement Start
             * Format: date
             */
            statement_start: string;
            /**
             * Statement End
             * Format: date
             */
            statement_end: string;
            /** Closing Date */
            closing_date: string | null;
            /** Due Date */
            due_date: string | null;
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            status: components["schemas"]["StatementStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CardTransactionOut */
        CardTransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Credit Card Id
             * Format: uuid
             */
            credit_card_id: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Description Raw */
            description_raw: string;
            /** Description Norm */
            description_norm: string;
            /** Merchant Raw */
            merchant_raw: string | null;
            /** Amount Minor */
            amount_minor: number;
            /** Currency */
            currency: string;
            /** Installments Total */
            installments_total: number | null;
            /** Installment Number */
            installment_number: number | null;
            /** Fingerprint Hash */
            fingerprint_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Category Id */
            category_id?: string | null;
            /** Category Name */
            category_name?: string | null;
        };
        /** CategorizationOut */
        CategorizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            target_type: components["schemas"]["TargetType"];
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Confidence */
            confidence: number | null;
            source: components["schemas"]["CategorizationSource"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CategorizationSource
         * @enum {string}
         */
        CategorizationSource: "manual" | "rule" | "system";
        /** CategorizeRequest */
        CategorizeRequest: {
            target_type: components["schemas"]["TargetType"];
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Confidence */
            confidence?: number | null;
            /** @default manual */
            source: components["schemas"]["CategorizationSource"];
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            kind: components["schemas"]["CategoryKind"];
            /** Parent Id */
            parent_id?: string | null;
        };
        /**
         * CategoryKind
         * @enum {string}
         */
        CategoryKind: "expense" | "income" | "transfer";
        /** CategoryOut */
        CategoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["CategoryKind"];
            /** Parent Id */
            parent_id: string | null;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            kind?: components["schemas"]["CategoryKind"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatchOut */
        ImportBatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Filename */
            filename: string;
            /** Sha256 */
            sha256: string;
            status: components["schemas"]["ImportStatus"];
            /** Inserted Count */
            inserted_count: number;
            /** Duplicate Count */
            duplicate_count: number;
            /** Error Count */
            error_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Processed At */
            processed_at: string | null;
        };
        /**
         * ImportStatus
         * @enum {string}
         */
        ImportStatus: "created" | "processed" | "failed";
        /** InstrumentCreate */
        InstrumentCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["InstrumentType"];
            source: components["schemas"]["InstrumentSource"];
            /** Currency */
            currency: string;
            /**
             * Source Instrument Id
             * @default
             */
            source_instrument_id: string;
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            } | null;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            type: components["schemas"]["InstrumentType"];
            source: components["schemas"]["InstrumentSource"];
            /** Currency */
            currency: string;
            /** Source Instrument Id */
            source_instrument_id: string;
            /** Metadata */
            metadata_: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * InstrumentSource
         * @enum {string}
         */
        InstrumentSource: "santander_br" | "xp_br" | "bbva_uy";
        /**
         * InstrumentType
         * @enum {string}
         */
        InstrumentType: "bank_account" | "credit_card";
        /** InstrumentUpdate */
        InstrumentUpdate: {
            /** Name */
            name?: string | null;
            /** Metadata */
            metadata_?: {
                [key: string]: unknown;
            } | null;
        };
        /** SpendingByCategory */
        SpendingByCategory: {
            /** Category Name */
            category_name: string;
            category_kind: components["schemas"]["CategoryKind"];
            /** Total Minor */
            total_minor: number;
            /** Currency */
            currency: string;
            /** Transaction Count */
            transaction_count: number;
        };
        /** SpendingSummaryOut */
        SpendingSummaryOut: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** By Category */
            by_category: components["schemas"]["SpendingByCategory"][];
            /** Uncategorized Minor */
            uncategorized_minor: number;
            /** Total Minor */
            total_minor: number;
        };
        /**
         * StatementStatus
         * @enum {string}
         */
        StatementStatus: "open" | "closed" | "paid" | "partial";
        /**
         * TargetType
         * @enum {string}
         */
        TargetType: "bank_transaction" | "card_transaction";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_instruments_instruments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
        };
    };
    create_instrument_instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instrument_instruments__instrument_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstrumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_import_batches_imports_get: {
        parameters: {
            query?: {
                instrument_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_batch_imports__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_imports_upload_post: {
        parameters: {
            query: {
                instrument_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_imports_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bank_transactions_bank_transactions_get: {
        parameters: {
            query?: {
                instrument_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                category_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankTransactionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_card_transactions_card_transactions_get: {
        parameters: {
            query?: {
                instrument_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                category_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardTransactionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_statements_card_statements_get: {
        parameters: {
            query?: {
                instrument_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardStatementOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_category_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categorize_categorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategorizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categorize_bulk_categorize_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCategorizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkCategorizeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_categorization_categorizations__categorization_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categorization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spending_summary_spending_summary_get: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
                instrument_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
